#!/bin/bash
set -x

if [ ! -d ${OPENSHIFT_DATA_DIR}jdk1.8.0_31 ]
    then
        echo "Installing Java 8"
        cd ${OPENSHIFT_DATA_DIR}
        wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u31-b13/jdk-8u31-linux-x64.tar.gz
        tar xvf *.tar.gz
        rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.2.1 ]
    then
        echo "Installing Gradle 2.2.1"
        cd $OPENSHIFT_DATA_DIR
        wget https://services.gradle.org/distributions/gradle-2.2.1-bin.zip
        unzip gradle-2.2.1-bin.zip
        rm -f gradle-2.2.1-bin.zip
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle ]
    then
        cd $OPENSHIFT_DATA_DIR
        mkdir gradle
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
    then
        cd $OPENSHIFT_DATA_DIR
        mkdir logs
fi
